Add DUMP permission for Fastlane screenshot testing
Fastlane tries to grant android.permission.DUMP during screenshot
testing, but the permission wasn't declared in the manifest.

Added DUMP permission to debug manifest to fix:
  java.lang.SecurityException: Package org.codeberg.theoden8.webspace
  has not requested permission android.permission.DUMP

This permission is only included in debug builds and is used by
Fastlane for debugging/testing purposes.